### ISSUE TITLE
Quality parameter ignored

### ISSUE THREAD

**Issue by mirkoclemente** [flokosiol/kirby-focus#13]
Hi,

on my machine focusCrop seems to ignore the quality parameter.

$image->focusCrop($width, $height, X);
creates always the same image unaffected by X.

$image->crop($width, $height, X);
works as expected and appends the quality parameter (-qX.ext) to the filename.

I would appreciate any help on this issue.

**Comment by flokosiol** [comment]
Thanks for reporting. As you mention correctly, `focusCrop()` doesn't add `-qX` to the [filename](https://github.com/flokosiol/kirby-focus/blob/master/methods/file.php#L52). This means that Kirby doesn't recreate the thumb, if the quality changes.

**Flushing your thumbs folder** should force Kirby to recreate the images.

I'm already working on this issue, because there will be a [possibility to use more parameters](https://github.com/flokosiol/kirby-focus/issues/12) than `quality` in the future. As you can see in the [develop branch](https://github.com/flokosiol/kirby-focus/blob/develop/methods/file.php#L61) I tried to use a hash which respects all possible parameters, but this leads to unreadable filenames … I'm not sure, if this is the best solution.

As a quick fix you could change [line 55](https://github.com/flokosiol/kirby-focus/blob/master/methods/file.php#L55) of `methods/file.php` to this …

```
if ($quality) {
  $params['quality'] = $quality;
  $params['filename'] = '{safeName}-' . $params['width'] . 'x' . $params['height'] . '-' . $params['focusX']*100 . '-' . $params['focusY']*100 . '-q' . $params['quality'] . '.{extension}';
}
```

**Comment by mirkoclemente** [comment]
Thank you for the clarification and the little fix. I'm looking forward to the new features.
