### ISSUE TITLE
Gif resizing down increases file size

### ISSUE THREAD

**Issue by MichaelPrecel** [flokosiol/kirby-focus#25]
Hey @flokosiol,

This plugin is so intelligent and useful – thanks!

I'm having a bit of a problem however with using it to resize gifs down to a smaller pixel dimension, it results in a considerably larger file size. For example, a 1000 x 1000px gif at 1.27mb when scaled down to 400 x 400px become 2mb and at 800 x 800px becomes 8.4mb. 

I'm assuming this has something to do with the imageMagick driver, but can the settings on your plugin be used to fix this? Perhaps by using -scale instead of -resize ( https://www.imagemagick.org/discourse-server/viewtopic.php?t=29205 )?

Any help is much appreciated!

**Comment by flokosiol** [comment]
Thanks for reporting. 

The Focus plugin IM driver inherits most of its logic from the [original IM thumb driver](https://github.com/getkirby/toolkit/blob/master/lib/thumb.php#L273) of the Kirby Toolkit, including the [-resize](https://github.com/getkirby/toolkit/blob/master/lib/thumb.php#L299) option.

Could you please verify, if the issue also occures when you are using `crop()` instead of `focusCrop()`? In this case it is a Toolkit issue, too.

I will check your suggestion, but this will take some time. In the meantime you can change the option by yourself to do some tests, if you like. You can change [line 32 in site/plugin/focus/drivers/im.php](https://github.com/flokosiol/kirby-focus/blob/master/drivers/im.php#L32), which is responsible for the `focusCrop()` method. There are two more lines with `-resize` below for `crop()` and when the image ratio doesn't change.

**Comment by MichaelPrecel** [comment]
Thanks so much for getting back to me promptly.

I have just run a quick test and it appears to happen using the crop() method as well. I tried previously altering the im.php file to change the -resize option to -scale, but also no luck. 

From a bit of research it appears to be caused by the fact that IM is incapable of optimising resized gifs, which is a shame, and some suggestions seem to prefer other image drivers (eg Gifsicle), which is also not much help!

Let me know if you have any other ideas! Thanks again.

**Comment by flokosiol** [comment]
Alright. Thanks for the quick response and the testing.

**Comment by flokosiol** [comment]
Seems to be an ImageMagick issue, so I will close this one here.
