### ISSUE TITLE
Cannot use a scalar value as an array

### ISSUE THREAD

**Issue by carstengrimm** [flokosiol/kirby-focus#32]
Inside the focus/config.php it seems that something is breaking the whole thing. I have pretty much a basic setup with latest k-next focus as well as latest beta and made sure all files have templates.

![image](https://user-images.githubusercontent.com/5014509/47940905-6f8d9d00-deec-11e8-8f28-f2b6660319ec.png)

**Comment by carstengrimm** [comment]
temporary fix is to declare inside the function first

```
$options = array(); 
```

**Comment by flokosiol** [comment]
Unfortunately this is no practical fix, because `focusCrop()` accepts options as third parameter, which need to be passed as an array. 

In K2 there was a (deprecated) Option, that the 3rd Parameter could also be an integer, which was then used as *quality*. This is no longer supported. 

The error ”Cannot use skalar value …“ indicates, that you probably use the old syntax `focusCrop(200,300,80)` instead of `focusCrop(200,300,['quality' => 80])`. Could you please check that?

**Comment by carstengrimm** [comment]
you are correct. i was using the old syntax
