### ISSUE TITLE
Plugins stretches/rotates images with certain EXIF settings

### ISSUE THREAD

**Issue by jonasfeige** [flokosiol/kirby-focus#50]
Not sure if this is jut me, but when using the focus plugin, uploaded images with certain EXIF rotation settings get rotated/stretched.

### Step to reproduce
1. Download EXIF orientation sample images from this repo: [https://github.com/recurser/exif-orientation-examples](https://github.com/recurser/exif-orientation-examples)
2. Download and setup Kirby Starterkit: [https://github.com/getkirby/starterkit](https://github.com/getkirby/starterkit)
3. Login to the panel and navigate to any album (e.g. Photograph->Trees)
4. Upload the sample photos, everything should work as expected
5. Download and install the Focus plugin
6. Delete the sample photos or navigate to another album
7. Upload the sample photos again, numbers 5-8 will be stretched and/or rotated in the wrong way

I [fixed this with a hook](https://forum.getkirby.com/t/problem-with-image-orientation-on-upload/13794/26) in the meantime.

**Comment by flokosiol** [comment]
First of all, thanks for this excellent description!

I went through the steps and ended up at no. 4 because the photos 5-8 already get stretched on a **fresh starterkit installation without any additional plugins** – at least for me. Pleaser find attached the screenshots from the Panel. 

Starterkit 3.3.5 
ImageMagick 7.0.10-6_1

The [ImageMagick class used by the Focus plugin](https://github.com/flokosiol/kirby-focus/blob/master/src/Focus/ImageMagick.php) is almost the same as the one used by [Kirby](https://github.com/getkirby/kirby/blob/master/src/Image/Darkroom/ImageMagick.php). So this issue might be Kirby related, @bastianallgeier!?

<img width="1552" alt="stretched-images-1" src="https://user-images.githubusercontent.com/11918336/79700605-29bac500-8297-11ea-8a36-381342cafa9a.png">
<img width="1552" alt="stretched-images-2" src="https://user-images.githubusercontent.com/11918336/79700610-36d7b400-8297-11ea-9724-a3888179f734.png">

**Comment by jonasfeige** [comment]
Ah, interesting! I first thought it might be a Kirby issue as well.
Have you tried if the [auto-orient setting for thumbs](https://getkirby.com/docs/reference/system/options/thumbs#auto-orient) has any effect? It didn’t for me, unfortunately.

**Comment by flokosiol** [comment]
Auto-orient had no effect for me, too. 

I close the issue for now as it seem to be Kirby related. If you run into any issues with this plugin again, don't hesitate to contact me again!
